modLoader="javafml" 
loaderVersion="[45,)" 
license="All rights reserved"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"
[[mods]] 
modId="pmmogating" 
version="${file.jarVersion}" 
displayName="Project MMO - Gating"
#updateJSONURL="https://change.me.example.invalid/updates.json" 
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" 
#logoFile="pmmo.png" 
credits="The Community and Contributors of the Project" 
authors="Project RPG Team and Contributors" 
#displayTest="MATCH_VERSION" 
description='''
Project MMO - Gating is an addon to Project RPG which provides gating
in the style of Project MMO.
'''

[[dependencies.pmmogating]]
    modId="forge" 
    mandatory=true 
    versionRange="[45,)" 
    ordering="NONE"
    side="BOTH"
	
[[dependencies.pmmogating]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"
